spring:
  application:
    name: obavijesti-dokumentacija

  datasource:
    url: jdbc:mysql://localhost:3306/mikroservis_tri?createDatabaseIfNotExist=TRUE&useSSL=FALSE&allowPublicKeyRetrieval=TRUE&serverTimezone=UTC
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: true
        type:
          descriptor:
            sql: TRACE
            sql.BasicBinder: TRACE

  cloud:
    client:
      hostname: localhost
    inetutils:
      ignored-interfaces: [".*"]
      preferred-networks: ["127.0.0.1"]

server:
  port: 8084
  servlet:
    context-path: /obavijesti-dokumentacija

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadataMap:
      context-path: /obavijesti-dokumentacija
    healthCheckUrlPath: /obavijesti-dokumentacija/actuator/health
    statusPageUrlPath: /obavijesti-dokumentacija/actuator/info

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type.descriptor.sql: TRACE
        type.descriptor.sql.BasicBinder: TRACE
        stat: DEBUG
      springframework:
        web: DEBUG
        security: DEBUG
        cloud: DEBUG
        amqp: DEBUG
    com.netflix: DEBUG
    springdoc: DEBUG
    root: INFO
