// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_events.proto

// Protobuf Java Version: 3.25.1
package grpc;

public interface LogEventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.LogEventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
