// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_events.proto

// Protobuf Java Version: 3.25.1
package grpc;

public interface SystemEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:events.SystemEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>string microservice_name = 2;</code>
   * @return The microserviceName.
   */
  java.lang.String getMicroserviceName();
  /**
   * <code>string microservice_name = 2;</code>
   * @return The bytes for microserviceName.
   */
  com.google.protobuf.ByteString
      getMicroserviceNameBytes();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.events.ActionType action_type = 4;</code>
   * @return The enum numeric value on the wire for actionType.
   */
  int getActionTypeValue();
  /**
   * <code>.events.ActionType action_type = 4;</code>
   * @return The actionType.
   */
  ActionType getActionType();

  /**
   * <code>string resource_name = 5;</code>
   * @return The resourceName.
   */
  java.lang.String getResourceName();
  /**
   * <code>string resource_name = 5;</code>
   * @return The bytes for resourceName.
   */
  com.google.protobuf.ByteString
      getResourceNameBytes();

  /**
   * <pre>
   * ID ili jedinstveni identifikator resursa
   * </pre>
   *
   * <code>string resource_identifier = 6;</code>
   * @return The resourceIdentifier.
   */
  java.lang.String getResourceIdentifier();
  /**
   * <pre>
   * ID ili jedinstveni identifikator resursa
   * </pre>
   *
   * <code>string resource_identifier = 6;</code>
   * @return The bytes for resourceIdentifier.
   */
  com.google.protobuf.ByteString
      getResourceIdentifierBytes();

  /**
   * <code>.events.ResponseStatus response_status = 7;</code>
   * @return The enum numeric value on the wire for responseStatus.
   */
  int getResponseStatusValue();
  /**
   * <code>.events.ResponseStatus response_status = 7;</code>
   * @return The responseStatus.
   */
  ResponseStatus getResponseStatus();

  /**
   * <code>string error_message = 8;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 8;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();

  /**
   * <code>map&lt;string, string&gt; additional_info = 9;</code>
   */
  int getAdditionalInfoCount();
  /**
   * <code>map&lt;string, string&gt; additional_info = 9;</code>
   */
  boolean containsAdditionalInfo(
      java.lang.String key);
  /**
   * Use {@link #getAdditionalInfoMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAdditionalInfo();
  /**
   * <code>map&lt;string, string&gt; additional_info = 9;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAdditionalInfoMap();
  /**
   * <code>map&lt;string, string&gt; additional_info = 9;</code>
   */
  /* nullable */
java.lang.String getAdditionalInfoOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; additional_info = 9;</code>
   */
  java.lang.String getAdditionalInfoOrThrow(
      java.lang.String key);
}
