// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_events.proto

// Protobuf Java Version: 3.25.1
package grpc;

public final class SystemEventsProto {
  private SystemEventsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_SystemEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_SystemEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_SystemEvent_AdditionalInfoEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_SystemEvent_AdditionalInfoEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_events_LogEventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_events_LogEventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023system_events.proto\022\006events\032\037google/pr" +
      "otobuf/timestamp.proto\"\206\003\n\013SystemEvent\022-" +
      "\n\ttimestamp\030\001 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\031\n\021microservice_name\030\002 \001(\t\022\017\n\007user" +
      "_id\030\003 \001(\t\022\'\n\013action_type\030\004 \001(\0162\022.events." +
      "ActionType\022\025\n\rresource_name\030\005 \001(\t\022\033\n\023res" +
      "ource_identifier\030\006 \001(\t\022/\n\017response_statu" +
      "s\030\007 \001(\0162\026.events.ResponseStatus\022\025\n\rerror" +
      "_message\030\010 \001(\t\022@\n\017additional_info\030\t \003(\0132" +
      "\'.events.SystemEvent.AdditionalInfoEntry" +
      "\0325\n\023AdditionalInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005" +
      "value\030\002 \001(\t:\0028\001\"4\n\020LogEventResponse\022\017\n\007s" +
      "uccess\030\001 \001(\010\022\017\n\007message\030\002 \001(\t*V\n\nActionT" +
      "ype\022\033\n\027ACTION_TYPE_UNSPECIFIED\020\000\022\n\n\006CREA" +
      "TE\020\001\022\007\n\003GET\020\002\022\n\n\006UPDATE\020\003\022\n\n\006DELETE\020\004*I\n" +
      "\016ResponseStatus\022\037\n\033RESPONSE_STATUS_UNSPE" +
      "CIFIED\020\000\022\013\n\007SUCCESS\020\001\022\t\n\005ERROR\020\0022P\n\023Even" +
      "tLoggingService\0229\n\010LogEvent\022\023.events.Sys" +
      "temEvent\032\030.events.LogEventResponseB-\n\026co" +
      "m.system_events.grpcB\021SystemEventsProtoP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_events_SystemEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_events_SystemEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_SystemEvent_descriptor,
        new java.lang.String[] { "Timestamp", "MicroserviceName", "UserId", "ActionType", "ResourceName", "ResourceIdentifier", "ResponseStatus", "ErrorMessage", "AdditionalInfo", });
    internal_static_events_SystemEvent_AdditionalInfoEntry_descriptor =
      internal_static_events_SystemEvent_descriptor.getNestedTypes().get(0);
    internal_static_events_SystemEvent_AdditionalInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_SystemEvent_AdditionalInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_events_LogEventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_events_LogEventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_events_LogEventResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
