server:
  port: 8082
  servlet:
    context-path: /auth
spring:
  application:
    name: login-registracija-aplikacija
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: password123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: termini.pregledi@gmail.com
    password: ztxwukwxlxykgrye
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.trust: smtp.gmail.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${eureka.instance.ip-address}:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadataMap:
      context-path: /auth

application:
  security:
    jwt:
      secret-key: ajy+bmnRSy1+SuXXIY+kwLj/Nq7Z7QKPZBBN8Tl6XMzjZm2v3++Yvdd8CA83TBLA1lbeVSGR7eysm6tFg3/TVA==
      expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG
    org.com.medicinska.rezervacija.apigateway.filter: DEBUG
    org.com.medicinska.rezervacija.apigateway.security: DEBUG